#2.	Crear un programa utilizando Python que le permita sacar 
#<el promedio de 3 notas ingresadas por el teclado, y debe de 
#mostrar el promedio.


print("Promedio de 3 numeros")
num1=float(input("Ingrese la 1er nota "))
num2=float(input("Ingrese la 2da nota "))
num3=float(input("Ingrese la 3er nota "))


sum=num1+num2+num3
prom=sum/3
print("El promedio de las notas dadas es: ", prom)

